### PR TITLE
Update cms-monitoring.cern.ch front-end 

### PR DESCRIPTION
**Pull request by nikodemas**
Some small changes in the `html` code of the [cms-monitoring.cern.ch](https://cms-monitoring.cern.ch/)

FYI @vkuznet @leggerf @brij01

### CODE REVIEW

**Comment by vkuznet** [comment]
+1

**Comment by leggerf** [comment]
+1

**Comment by nikodemas** [comment]
@vkuznet should I ask for developer's rights or you want to merge it? Because currently I cannot merge it

**Comment by vkuznet** [comment]
I'm merging it now, but I don't see any issues if you'll request developers rights to this project.

**Pull request merged**
